### ISSUE TITLE
Allow user to timestamp text input.

### ISSUE THREAD

**Issue by degeri** [decred/authit#24]
Right now we are allowing users to upload a "file" to get timestamped. We could also do the same for "text" by offering a "text" form. This has alot of uses. And will drive adaptation. 

Of course someone could just type the "text" into a file and upload it. But I feel having a separate text input box on the site itself will be very cool.

**Comment by degeri** [comment]
Anyone who is too lazy/unable (on a mobile device) to create a text file and upload it. 
Someone can choose to timestamp a hash for tweeter.
eg type in: 
"I predict that bitcoin will cross 5000 USD by 31 Dec 2018" and tweet out the dcrtime stamp. Then prove later that they predicted right.

**Comment by vctt94** [comment]
I can take this one
