### ISSUE TITLE
Apply better filters for file name's

### ISSUE THREAD

**Issue by degeri** [decred/authit#28]
Hi I was testing some inputs and observed that most HTML special characters are escaped in but in the title value < , > are not getting escaped to \&lt;  or \&gt; .

In the screenshot below you can see I have submitted a file named. controlchar\<this\> in one location it is getting escaped to controlchar\&lt;this\&gt; but in others location it is set to title="controlchar\<this\>"

\" is being escaped to \&quot; so I was unable to make as xss but it is still recommended to fix this.

![image](https://user-images.githubusercontent.com/41839293/50341709-e38c0f00-0545-11e9-932a-dc289dc1b38d.png)

![image](https://user-images.githubusercontent.com/41839293/50341713-e8e95980-0545-11e9-849b-0d2baeb1eccf.png)

**Comment by vctt94** [comment]
I believe we can close this one. 

After #45 got merged, it changed how we show files name. We are only using jsx for that now and jsx is already protected against xss attacks: https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks

![image](https://user-images.githubusercontent.com/15069783/54710600-cce65b80-4b26-11e9-96dd-9d32ad2fc240.png)

What is your opinion on that @degeri ?

**Comment by degeri** [comment]
Yes this is fine .. Closing the issue.
