### ISSUE TITLE
Create a route to verify a SHA256 digest

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/authit#46]
We need a route to verify a single digest so people can share the link with the proof. A good idea would be `results/:digest`. In this route we should make a request to `/verify` to see if the digest is anchored. I don't think it's a good idea to call `/timestamp` in this route, so it would have just two states: _anchored_ and _not anchored_. Digests already submitted to dcrtime but waiting to be flushed would be classified as _not anchored_.

**Comment by fernandoabolafio** [comment]
What if we use the results route I introduced in my PR? it is already verifying the provided hashes in the URL, the only modification we would need is flag like `?timestamp=true` which will timestamp the digests which aren't in the dcrtime yet.
